# Endpoint for CRON. Restart week spotlight
POST http://localhost:3000/api/spotlights

# key should match the key in env variables
{
  "key": "somekey"
}

### Endpoint to fake weekly spotlight participants
POST http://localhost:3000/api/spotlights/fake

# key should match the key in env variables
{
  "key": "somekey",
  "userIdsForSpotlight": ["JOB__SEEKING_USER_ID"]
}