export const tools = [
  "JavaScript",
  "HTML/CSS",
  "Python",
  "SQL",
  "TypeScript",
  "Bash/Shell (all shells)",
  "Java",
  "C#",
  "C++",
  "C",
  "PHP",
  "PowerShell",
  "Go",
  "Rust",
  "Kotlin",
  "Ruby",
  "Lua",
  "Dart",
  "Assembly",
  "Swift",
  "R",
  "Visual Basic (.Net)",
  "MATLAB",
  "VBA",
  "Groovy",
  "Delphi",
  "Scala",
  "Perl",
  "Elixir",
  "Objective-C",
  "Haskell",
  "GDScript",
  "Lisp",
  "Solidity",
  "Clojure",
  "Julia",
  "Erlang",
  "F#",
  "Fortran",
  "Prolog",
  "Zig",
  "Ada",
  "OCaml",
  "Apex",
  "Cobol",
  "SAS",
  "Crystal",
  "Nim",
  "APL",
  "Flow",
  "Raku",
  "PostgreSQL",
  "MySQL",
  "SQLite",
  "MongoDB",
  "Microsoft SQL Server",
  "Redis",
  "MariaDB",
  "Elasticsearch",
  "Oracle",
  "Dynamodb",
  "Firebase Realtime Database",
  "Cloud Firestore",
  "BigQuery",
  "Microsoft Access",
  "H2",
  "Cosmos DB",
  "Supabase",
  "InfluxDB",
  "Cassandra",
  "Snowflake",
  "Neo4J",
  "IBM DB2",
  "Solr",
  "Firebird",
  "Couch DB",
  "Clickhouse",
  "Cockroachdb",
  "Couchbase",
  "DuckDB",
  "Datomic",
  "RavenDB",
  "TiDB",
  "Amazon Web Services (AWS)",
  "Microsoft Azure",
  "Google Cloud",
  "Firebase",
  "Cloudflare",
  "Digital Ocean",
  "Heroku",
  "Vercel",
  "Netlify",
  "VMware",
  "Hetzner",
  "Linode, now Akamai",
  "Managed Hosting",
  "OVH",
  "Oracle Cloud Infrastructure (OCI)",
  "OpenShift",
  "Fly.io",
  "Vultr",
  "Render",
  "OpenStack",
  "IBM Cloud Or Watson",
  "Scaleway",
  "Colocation",
  "Node.js",
  "React",
  "jQuery",
  "Express",
  "Angular",
  "Next.js",
  "ASP.NET CORE",
  "Vue.js",
  "WordPress",
  "ASP.NET",
  "Flask",
  "Spring Boot",
  "Django",
  "Laravel",
  "FastAPI",
  "AngularJS",
  "Svelte",
  "Ruby on Rails",
  "NestJS",
  "Blazor",
  "Nuxt.js",
  "Symfony",
  "Deno",
  "Gatsby",
  "Fastify",
  "Phoenix",
  "Drupal",
  "CodeIgniter",
  "Solid.js",
  "Remix",
  "Elm",
  "Play Framework",
  "Lit",
  "Qwik",
  ".NET (5+)",
  "NumPy",
  "Pandas",
  ".NET Framework (1.0 - 4.8)",
  "Spring Framework",
  "RabbitMQ",
  "TensorFlow",
  "Scikit-Learn",
  "Flutter",
  "Apache Kafka",
  "Torch/PyTorch",
  "React Native",
  "Opencv",
  "Electron",
  "OpenGL",
  "Qt",
  "CUDA",
  "Keras",
  "Apache Spark",
  "SwiftUI",
  "Xamarin",
  "Ionic",
  "Hugging Face Transformers",
  "GTK",
  "Cordova",
  ".NET MAUI",
  "Hadoop",
  "Tauri",
  "Capacitor",
  "Tidyverse",
  "Quarkus",
  "Ktor",
  "MFC",
  "JAX",
  "Micronaut",
  "Uno Platform",
  "Docker",
  "npm",
  "Pip",
  "Homebrew",
  "Yarn",
  "Webpack",
  "Make",
  "Kubernetes",
  "NuGet",
  "Maven (build tool)",
  "Gradle",
  "Vite",
  "Visual Studio Solution",
  "CMake",
  "Cargo",
  "GNU GCC",
  "Terraform",
  "MSBuild",
  "Ansible",
  "Chocolatey",
  "Composer",
  "LLVM's Clang",
  "APT",
  "Unity 3D",
  "Pacman",
  "pnpm",
  "MSVC",
  "Podman",
  "Ninja",
  "Unreal Engine",
  "Godot",
  "Ant",
  "Google Test",
  "Nix",
  "Meson",
  "QMake",
  "Puppet",
  "Dagger",
  "Chef",
  "Catch2",
  "Pulumi",
  "Bun",
  "Wasmer",
  "doctest",
  "SCons",
  "bandit",
  "cppunit",
  "Boost.Test",
  "build2",
  "tunit",
  "lest",
  "snitch",
  "CUTE",
  "ELFspy",
  "liblittletest",
  "Visual Studio Code",
  "Visual Studio",
  "IntelliJ IDEA",
  "Notepad++",
  "Vim",
  "Android Studio",
  "PyCharm",
  "Jupyter Notebook/JupyterLab",
  "Sublime Text",
  "Neovim",
  "Eclipse",
  "Xcode",
  "Nano",
  "WebStorm",
  "PhpStorm",
  "Atom",
  "Rider",
  "DataGrip",
  "CLion",
  "IPython",
  "Emacs",
  "VSCodium",
  "Goland",
  "Netbeans",
  "RStudio",
  "Code::Blocks",
  "Qt Creator",
  "Rad Studio (Delphi, C++ Builder)",
  "Fleet",
  "Helix",
  "Kate",
  "Spyder",
  "RubyMine",
  "Geany",
  "BBEdit",
  "TextMate",
  "Micro",
  "Nova",
  "condo",
  "Jira",
  "Confluence",
  "Markdown File",
  "Trello",
  "Notion",
  "GitHub Discussions",
  "Azure Devops",
  "Miro",
  "Wikis",
  "Asana",
  "Clickup",
  "Doxygen",
  "Redmine",
  "Monday.com",
  "Stack Overflow for Teams",
  "YouTrack",
  "Microsoft Planner",
  "Airtable",
  "Linear",
  "Basecamp",
  "Microsoft Lists",
  "Smartsheet",
  "Shortcut",
  "Wrike",
  "Adobe Workfront",
  "Redocly",
  "Document360",
  "Nuclino",
  "Swit",
  "Dingtalk (Teambition)",
  "Tettra",
  "Workzone",
  "Planview Projectplace Or Clarizen",
  "Wimi",
  "Cerri",
  "Leankor",
  "Microsoft Teams",
  "Slack",
  "Zoom",
  "Discord",
  "Google Meet",
  "Whatsapp",
  "Telegram",
  "Skype",
  "Signal",
  "Google Chat",
  "Cisco Webex Teams",
  "Mattermost",
  "Jitsi",
  "Matrix",
  "IRC",
  "Rocketchat",
  "Zulip",
  "Ringcentral",
  "Symphony",
  "Wire",
  "Wickr",
  "Unify Circuit",
  "Coolfire Core",
  "ChatGPT",
  "Bing AI",
  "WolframAlpha",
  "Google Bard AI",
  "Phind",
  "You.com",
  "Other (please specify)",
  "Perplexity AI",
  "Quora Poe",
  "Neeva AI",
  "Andi",
  "Metaphor",
  "GitHub Copilot",
  "Tabnine",
  "AWS CodeWhisperer",
  "Synk Code",
  "Codeium",
  "Whispr AI",
  "Replit Ghostwriter",
  "Mintlify",
  "Adrenaline",
  "Rubber Duck.AI",
];

export const skills = [
  "Developer, full-stack",
  "Developer, back-end",
  "Developer, front-end",
  "Developer, desktop or enterprise applications",
  "Developer, mobile",
  "Engineering manager",
  "Student",
  "Developer, embedded applications or devices",
  "Data scientist or machine learning specialist",
  "DevOps specialist",
  "Academic researcher",
  "Research & Development role",
  "Senior Executive (C-Suite, VP, etc.)",
  "Engineer, data",
  "Cloud infrastructure engineer",
  "Developer, game or graphics",
  "Data or business analyst",
  "System administrator",
  "Project manager",
  "Developer, QA or test",
  "Security professional",
  "Product manager",
  "Engineer, site reliability",
  "Educator",
  "Scientist",
  "Developer Experience",
  "Blockchain",
  "Hardware Engineer",
  "Designer",
  "Database administrator",
  "Developer Advocate",
  "Marketing or sales professional",
];

export const degreeTypes = [
  "Associate",
  "Bachelor",
  "Master",
  "Doctorate",
  "Professional",
  "Certification",
  "Technical Degree"
]
